### ISSUE TITLE
Anticheat Issues

### ISSUE THREAD

**Issue by d3athbl0w** [Lillecarl/mangos-tbc#32] opened 2019-04-21 04:36 UTC
1) A player was taming a Surf Crawler for my hunter class quest, and after he had the Crawler tamed and was on he way back to Razor Hill .. he got teleported back to where he tamed the Crawler.. without the Crawler as a pet.

2) I was on the elevator to Freewind Post in 1k Needles .. and it rolled me back to no thinking I was on the elevator.

**Comment by Lillecarl** [comment] 2020-10-26 23:11
Hi!

For issue number 1 i do not understand what you mean, i didn't really play much wow so retail stuff i don't really know alot about.

For issue number 2 i can't reproduce this on HEAD.

I'm closing this issue, please feel free to test the issues again and i will happily look at them.

**Closed as completed by Lillecarl** 2020-10-26 23:11 UTC
